name: "Extract content from a PR's diff"
description: "Uses a regex to extract content from a PR's diff."
author: "AlexanderWert"
branding:
  icon: "git-pull-request"
  color: "gray-dark"
inputs:
  github-token:
    description: "Github token, added magically"
    reguired: true
  pathToScan:
    description: "Path or prefix of files to scan the diff for."
    reguired: false
    default: ""
  newFilesOnly:
    description: "Scan only new files"
    reguired: false
    default: false
  regex:
    reguired: true
    description: "Regex to use for content extraction. Must contain exactly one regex group."
  indexGroupToCapture:
    required: false
    description: "The index (starting with 1) of the regex group to extract values from."
    default: 1
outputs:
  capturedContent:
    description: "The content captured through the regex group"

runs:
  using: "node20"
  main: "dist/index.js"
